use_frameworks!

platform :ios, '9.0'

target 'DqData_Example' do
  pod 'DqData', :path => '../'

  target 'DqData_Tests' do
    inherit! :search_paths

    pod 'FBSnapshotTestCase' , '~> 2.1.4'
  end
end
